language: node_js

sudo: false

# test on node.js versions
node_js:
  - '14'
  - '12'
  - '10'

services:
  - redis-server

script:
  - yarn lint
  - yarn test

jobs:
  include:
    - stage: coverage
      node_js: lts/*
      script:
        - yarn coverage
        - yarn coveralls
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
